"""
Base Pattern Detection Framework

This module provides the abstract base class and data structures for all pattern detectors.

PERFORMANCE OPTIMIZATIONS (Phase 1):
- Optional window_start parameter to avoid DataFrame slicing
- NumPy array extraction for faster access
- Batch detection method for processing multiple bars
- Pre-allocated result arrays in detect_all()
- IndicatorCache support for pre-computed indicators

PERFORMANCE OPTIMIZATIONS (Phase 2):
- detect_vectorized() for array-based pattern detection
- precompute_signals() for caching signals before backtest
- get_cached_signal() for O(1) signal lookup
- Numba JIT compilation support in subclasses
"""

from abc import ABC, abstractmethod
from dataclasses import dataclass, field
from enum import Enum
from typing import TYPE_CHECKING, Any, Dict, List, Optional

import numpy as np
import pandas as pd

if TYPE_CHECKING:
    from src.indicators.indicator_cache import IndicatorCache


class RegimeState(Enum):
    """Market regime states for pattern compatibility."""

    TRENDING = "Trending"
    RANGING = "Ranging"
    VOLATILE = "Volatile"
    TRANSITION = "Transition"


class PatternType(Enum):
    """Classification of pattern types"""

    REVERSAL = "Reversal"
    CONTINUATION = "Continuation"
    BREAKOUT = "Breakout"
    COUNTER_TREND = "Counter-Trend Reversal"
    VOLATILITY = "Volatility Breakout/Reversal"


class SignalDirection(Enum):
    """Trading signal direction"""

    LONG = "Long"
    SHORT = "Short"
    NEUTRAL = "Neutral"


@dataclass
class TradeSignal:
    """
    Trade signal generated by pattern detection.

    Attributes:
        pattern_name: Name of the detected pattern
        direction: Long or Short
        entry_price: Suggested entry price
        stop_loss: Stop loss price level
        take_profit_1: First take profit target
        take_profit_2: Second take profit target (optional)
        take_profit_3: Third take profit target (optional)
        confidence: Signal confidence score (0.0 to 1.0)
        timestamp: Bar timestamp when signal was generated
        metadata: Additional pattern-specific information
    """

    pattern_name: str
    direction: SignalDirection
    entry_price: float
    stop_loss: float
    take_profit_1: float
    take_profit_2: Optional[float] = None
    take_profit_3: Optional[float] = None
    confidence: float = 0.5
    timestamp: Optional[pd.Timestamp] = None
    metadata: Dict[str, Any] = field(default_factory=dict)

    def to_dict(self) -> Dict[str, Any]:
        """Convert signal to dictionary format"""
        return {
            "pattern_name": self.pattern_name,
            "direction": self.direction.value,
            "entry_price": self.entry_price,
            "stop_loss": self.stop_loss,
            "take_profit_1": self.take_profit_1,
            "take_profit_2": self.take_profit_2,
            "take_profit_3": self.take_profit_3,
            "confidence": self.confidence,
            "timestamp": str(self.timestamp) if self.timestamp else None,
            "metadata": self.metadata,
        }


@dataclass
class PatternResult:
    """
    Result of pattern detection at a specific bar.

    Attributes:
        detected: Whether the pattern was detected
        pattern_name: Name of the pattern
        pattern_type: Classification of the pattern
        signal: Generated trade signal (if any)
        pivot_points: Key price levels identified in the pattern
        bars_since_detection: Number of bars since pattern was first detected
        start_index: Bar index where pattern started
        end_index: Bar index where pattern completed
    """

    detected: bool
    pattern_name: str
    pattern_type: PatternType
    signal: Optional[TradeSignal] = None
    pivot_points: Dict[str, Any] = field(default_factory=dict)
    bars_since_detection: int = 0
    start_index: Optional[int] = None
    end_index: Optional[int] = None

    def to_dict(self) -> Dict[str, Any]:
        """Convert result to dictionary format"""
        return {
            "detected": self.detected,
            "pattern_name": self.pattern_name,
            "pattern_type": self.pattern_type.value,
            "signal": self.signal.to_dict() if self.signal else None,
            "pivot_points": self.pivot_points,
            "bars_since_detection": self.bars_since_detection,
            "start_index": self.start_index,
            "end_index": self.end_index,
        }


@dataclass
class BasePattern(ABC):
    """
    Abstract base class for all pattern detectors.

    All pattern implementations must inherit from this class and implement
    detect() and generate_signal() methods.

    Attributes:
        name: Pattern name
        pattern_type: Pattern classification
        min_bars_required: Minimum bars needed for
        preferred_regimes: Regimes where pattern works best (R4 enhancement)
        incompatible_regimes: Regimes where pattern should be avoided (R4 enhancement)

    Performance Optimizations:
        - _arrays: Cached NumPy arrays for faster access
        - _indicator_cache: Optional cache for pre-computed indicators
        - detect_batch(): Batch processing for multiple bars
    """

    name: str
    pattern_type: PatternType
    min_bars_required: int = 5
    preferred_regimes: List[RegimeState] = field(default_factory=list)
    incompatible_regimes: List[RegimeState] = field(default_factory=list)

    def __post_init__(self):
        # Performance optimization: cached arrays
        self._arrays: Optional[Dict[str, np.ndarray]] = None
        self._arrays_df_id: Optional[int] = None
        # Performance optimization: indicator cache reference
        self._indicator_cache: Optional["IndicatorCache"] = None
        # PHASE 2: Cached vectorized signals
        self._signals_cache: Optional[np.ndarray] = None
        self._signals_cache_df_id: Optional[int] = None

    def set_indicator_cache(self, cache: "IndicatorCache") -> None:
        """
        Set indicator cache for pre-computed indicators.

        Args:
            cache: IndicatorCache instance
        """
        self._indicator_cache = cache

    def is_regime_compatible(self, regime: RegimeState) -> bool:
        """
        Check if pattern is compatible with given regime (R4 enhancement).

        Args:
            regime: Current market regime

        Returns:
            True if pattern should be active in this regime
        """
        if regime in self.incompatible_regimes:
            return False

        if self.preferred_regimes and regime not in self.preferred_regimes:
            return False

        return True

    def get_regime_preference(self, regime: RegimeState) -> float:
        """
        Get pattern preference score for given regime (R4 enhancement).

        Args:
            regime: Current market regime

        Returns:
            Preference score: 1.0 (preferred), 0.5 (neutral), 0.0 (incompatible)
        """
        if regime in self.incompatible_regimes:
            return 0.0

        if regime in self.preferred_regimes:
            return 1.0

        if self.preferred_regimes:
            return 0.3

        return 0.5

    @abstractmethod
    def detect(self, df: pd.DataFrame, i: int, window_start: Optional[int] = None) -> PatternResult:
        """
        Detect pattern at bar index i.

        Args:
            df: DataFrame with OHLCV data (columns: Open, High, Low, Close, Volume)
            i: Current bar index to check for pattern
            window_start: Optional start index for window bounds (avoids DataFrame slicing)

        Returns:
            PatternResult containing detection status and any generated signal
        """
        pass

    @abstractmethod
    def generate_signal(self, df: pd.DataFrame, i: int) -> Optional[TradeSignal]:
        """
        Generate trade signal if pattern is detected.

        Args:
            df: DataFrame with OHLCV data
            i: Current bar index

        Returns:
            TradeSignal if valid entry point, None otherwise
        """
        pass

    def _validate_data(self, df: pd.DataFrame, i: int, window_start: Optional[int] = None) -> bool:
        """
        Validate that data has required columns and sufficient bars.

        Args:
            df: DataFrame to validate
            i: Current bar index
            window_start: Optional window start for bounds checking

        Returns:
            True if data is valid, False otherwise
        """
        required_columns = ["Open", "High", "Low", "Close", "Volume"]

        # Check required columns
        if not all(col in df.columns for col in required_columns):
            return False

        # Check sufficient bars with window bounds
        min_idx = window_start if window_start is not None else 0
        if i < max(min_idx + self.min_bars_required, self.min_bars_required) or i >= len(df):
            return False

        return True

    def _extract_arrays(self, df: pd.DataFrame) -> Dict[str, np.ndarray]:
        """
        Extract NumPy arrays from DataFrame for faster access.

        Caches arrays for subsequent calls with the same DataFrame.

        Args:
            df: DataFrame with OHLCV data

        Returns:
            Dictionary with 'open', 'high', 'low', 'close', 'volume' arrays
        """
        # Use id() to detect if DataFrame changed (fast check)
        df_id = id(df)
        if self._arrays is not None and self._arrays_df_id == df_id:
            return self._arrays

        self._arrays = {
            "open": df["Open"].to_numpy(),
            "high": df["High"].to_numpy(),
            "low": df["Low"].to_numpy(),
            "close": df["Close"].to_numpy(),
            "volume": df["Volume"].to_numpy() if "Volume" in df.columns else np.array([]),
        }
        self._arrays_df_id = df_id
        return self._arrays

    def _get_bar_fast(self, arrays: Dict[str, np.ndarray], i: int) -> Optional[Dict[str, float]]:
        """
        Get bar data at index i using NumPy arrays (faster than DataFrame access).

        Args:
            arrays: Dictionary of NumPy arrays from _extract_arrays()
            i: Bar index

        Returns:
            Dictionary with 'open', 'high', 'low', 'close', 'volume' values or None if out of bounds
        """
        if i < 0 or i >= len(arrays["close"]):
            return None

        return {
            "open": float(arrays["open"][i]),
            "high": float(arrays["high"][i]),
            "low": float(arrays["low"][i]),
            "close": float(arrays["close"][i]),
            "volume": float(arrays["volume"][i]) if len(arrays["volume"]) > 0 else np.nan,
        }

    def _get_bar(self, df: pd.DataFrame, i: int, offset: int = 0) -> Optional[pd.Series]:
        """
        Get bar data at index i + offset.

        Args:
            df: DataFrame with OHLCV data
            i: Base index
            offset: Offset from base index (negative for lookback)

        Returns:
            Series containing bar data or None if out of bounds
        """
        idx = i + offset
        if 0 <= idx < len(df):
            return df.iloc[idx]
        return None

    def _safe_float(self, value) -> float:
        """Safely convert value to float, handling NaN and None"""
        if value is None:
            return np.nan
        if isinstance(value, pd.Series):
            value = value.iloc[0] if len(value) > 0 else np.nan
        try:
            result = float(value)
            return result if not np.isnan(result) else np.nan
        except (ValueError, TypeError):
            return np.nan

    def detect_batch(
        self,
        df: pd.DataFrame,
        start_idx: int,
        end_idx: int,
        window_start: Optional[int] = None,
    ) -> List[PatternResult]:
        """
        Detect patterns across a range of bars efficiently.

        Default implementation calls detect() for each bar.
        Subclasses can override for vectorized detection.

        Args:
            df: DataFrame with OHLCV data
            start_idx: Start bar index (inclusive)
            end_idx: End bar index (exclusive)
            window_start: Optional window start bound

        Returns:
            List of PatternResult objects for bars with detections
        """
        results = []
        for i in range(start_idx, end_idx):
            result = self.detect(df, i, window_start=window_start)
            if result.detected:
                results.append(result)
        return results

    def detect_vectorized(self, df: pd.DataFrame) -> np.ndarray:
        """
        Vectorized pattern detection across all bars.

        PHASE 2 OPTIMIZATION: Override this method in subclasses for optimal performance.
        Default implementation falls back to bar-by-bar detection.

        This method processes all bars at once using NumPy/Numba operations,
        which can be 50-100x faster than bar-by-bar detection.

        Args:
            df: DataFrame with OHLCV data

        Returns:
            numpy array of signal values:
            - 0 = no signal
            - 1 = long signal
            - -1 = short signal
        """
        # Default implementation - subclasses should override for performance
        n = len(df)
        signals = np.zeros(n, dtype=np.int8)

        for i in range(self.min_bars_required, n):
            result = self.detect(df, i)
            if result.detected and result.signal:
                if result.signal.direction == SignalDirection.LONG:
                    signals[i] = 1
                elif result.signal.direction == SignalDirection.SHORT:
                    signals[i] = -1

        return signals

    def precompute_signals(self, df: pd.DataFrame) -> None:
        """
        Pre-compute and cache signals for all bars.

        PHASE 2 OPTIMIZATION: Call this once before backtesting for maximum performance.
        The cached signals can then be accessed via get_cached_signal() in O(1) time.

        Args:
            df: DataFrame with OHLCV data
        """
        self._signals_cache = self.detect_vectorized(df)
        self._signals_cache_df_id = id(df)

    def get_cached_signal(self, i: int) -> int:
        """
        Get pre-computed signal for bar i.

        Args:
            i: Bar index

        Returns:
            Signal value: 0=none, 1=long, -1=short
        """
        if self._signals_cache is not None and i < len(self._signals_cache):
            return int(self._signals_cache[i])
        return 0

    def has_cached_signals(self, df: pd.DataFrame) -> bool:
        """
        Check if signals are cached for the given DataFrame.

        Args:
            df: DataFrame to check

        Returns:
            True if signals are cached for this DataFrame
        """
        return self._signals_cache is not None and self._signals_cache_df_id == id(df)

    def clear_cache(self) -> None:
        """Clear all cached data including signals and arrays."""
        self._signals_cache = None
        self._signals_cache_df_id = None
        self._arrays = None
        self._arrays_df_id = None

    def __repr__(self) -> str:
        return f"{self.__class__.__name__}(name='{self.name}', type={self.pattern_type.value})"


class PatternDetector:
    """
    Main pattern detection engine that runs all registered pattern detectors.

    Performance Optimizations:
        - Pre-allocated result arrays in detect_all()
        - Optional indicator cache for pre-computed indicators
        - Window bounds to avoid DataFrame slicing

    Usage:
        detector = PatternDetector()
        detector.register_pattern(MarketStructureLow())
        detector.register_pattern(MatchingLows())

        signals = detector.detect_all(df)
    """

    def __init__(self):
        self.patterns: List[BasePattern] = []
        self._indicator_cache: Optional["IndicatorCache"] = None

    def set_indicator_cache(self, cache: "IndicatorCache") -> None:
        """
        Set indicator cache for all registered patterns.

        Args:
            cache: IndicatorCache instance
        """
        self._indicator_cache = cache
        for pattern in self.patterns:
            if hasattr(pattern, "set_indicator_cache"):
                pattern.set_indicator_cache(cache)

    def register_pattern(self, pattern: BasePattern) -> None:
        """Register a pattern detector"""
        self.patterns.append(pattern)
        # Set indicator cache if available
        if self._indicator_cache and hasattr(pattern, "set_indicator_cache"):
            pattern.set_indicator_cache(self._indicator_cache)

    def detect_at_bar(
        self, df: pd.DataFrame, i: int, window_start: Optional[int] = None
    ) -> List[PatternResult]:
        """
        Run all pattern detectors at a specific bar.

        Args:
            df: DataFrame with OHLCV data
            i: Bar index to check
            window_start: Optional window start bound (avoids DataFrame slicing)

        Returns:
            List of PatternResult objects for all patterns
        """
        results = []
        for pattern in self.patterns:
            try:
                result = pattern.detect(df, i, window_start=window_start)
                results.append(result)
            except Exception as e:
                # Log error but continue with other patterns
                print(f"Error detecting {pattern.name} at bar {i}: {e}")
        return results

    def detect_all(self, df: pd.DataFrame) -> List[Dict[str, Any]]:
        """
        Run pattern detection across all bars with pre-allocated storage.

        Args:
            df: DataFrame with OHLCV data

        Returns:
            List of all detected signals with metadata
        """
        n_bars = len(df)
        n_patterns = len(self.patterns)

        # Pre-allocate result storage (worst case: all patterns at all bars)
        max_results = n_bars * n_patterns
        all_signals: List[Optional[Dict[str, Any]]] = [None] * max_results
        result_idx = 0

        # Get minimum bars required
        min_bars = max((p.min_bars_required for p in self.patterns), default=5)

        for i in range(min_bars, n_bars):
            results = self.detect_at_bar(df, i)
            for result in results:
                if result.detected and result.signal:
                    signal_dict = result.to_dict()
                    signal_dict["bar_index"] = i
                    all_signals[result_idx] = signal_dict
                    result_idx += 1

        # Trim unused slots
        return all_signals[:result_idx]  # type: ignore

    def detect_batch(self, df: pd.DataFrame, start_idx: int, end_idx: int) -> List[Dict[str, Any]]:
        """
        Run all pattern detectors across a batch of bars.

        Args:
            df: DataFrame with OHLCV data
            start_idx: Start bar index
            end_idx: End bar index

        Returns:
            List of all detected signals with metadata
        """
        all_signals = []
        window_start = max(0, start_idx - 200)

        for pattern in self.patterns:
            try:
                results = pattern.detect_batch(df, start_idx, end_idx, window_start)
                for result in results:
                    if result.signal:
                        signal_dict = result.to_dict()
                        signal_dict["bar_index"] = result.end_index
                        all_signals.append(signal_dict)
            except Exception as e:
                print(f"Error in batch detection for {pattern.name}: {e}")

        return all_signals

    def get_pattern_names(self) -> List[str]:
        """Get list of registered pattern names"""
        return [p.name for p in self.patterns]
