"""
ML Regime Classifier

Uses machine learning to enhance the rule-based ADX/ATR regime detector.
Supports multiple classifiers (Random Forest, Gradient Boosting, Logistic Regression).

Can:
1. Train on historical data with regime labels from rule-based detector
2. Predict regimes on new data
3. Provide feature importance analysis
4. Walk-forward validation with purged splits
"""

from __future__ import annotations

from enum import Enum
from typing import Any, Dict, List, Optional, Tuple

import numpy as np
import pandas as pd


class MLRegimeState(Enum):
    """ML-predicted regime states (aligned with rule-based detector)."""

    TRENDING = "Trending"
    RANGING = "Ranging"
    VOLATILE = "Volatile"
    TRANSITION = "Transition"


class RegimeClassifier:
    """
    ML-based regime classifier.

    Trains on features generated by FeatureEngineer and labels from
    the rule-based RegimeDetector.

    Example:
        >>> from src.ml.features import FeatureEngineer
        >>> from src.indicators.regime_detector import RegimeDetector
        >>>
        >>> eng = FeatureEngineer()
        >>> detector = RegimeDetector()
        >>>
        >>> classifier = RegimeClassifier(model_type="random_forest")
        >>> classifier.train(features, labels)
        >>> predictions = classifier.predict(new_features)
    """

    SUPPORTED_MODELS = ["random_forest", "gradient_boosting", "logistic_regression"]

    def __init__(
        self,
        model_type: str = "random_forest",
        n_estimators: int = 100,
        max_depth: Optional[int] = 3,
        random_state: int = 42,
        min_samples_leaf: int = 10,
        max_features: str = "sqrt",
    ):
        """
        Initialize regime classifier.

        Args:
            model_type: Type of classifier ("random_forest", "gradient_boosting", "logistic_regression")
            n_estimators: Number of trees (for tree-based models)
            max_depth: Maximum tree depth (reduced from 5 to 3 to prevent overfitting)
            random_state: Random seed for reproducibility
            min_samples_leaf: Minimum samples per leaf (regularization)
            max_features: Number of features per split (regularization)
        """
        if model_type not in self.SUPPORTED_MODELS:
            raise ValueError(
                f"Unknown model type: {model_type}. Supported: {self.SUPPORTED_MODELS}"
            )

        self.model_type = model_type
        self.n_estimators = n_estimators
        self.max_depth = max_depth
        self.random_state = random_state
        self.min_samples_leaf = min_samples_leaf
        self.max_features = max_features
        self.model = None
        self.classes_ = None
        self.feature_names_ = None

    def _create_model(self):
        """Create the underlying ML model with regularization."""
        from sklearn.ensemble import GradientBoostingClassifier, RandomForestClassifier
        from sklearn.linear_model import LogisticRegression

        if self.model_type == "random_forest":
            return RandomForestClassifier(
                n_estimators=self.n_estimators,
                max_depth=self.max_depth,
                min_samples_leaf=self.min_samples_leaf,
                max_features=self.max_features,
                random_state=self.random_state,
                class_weight="balanced",
            )
        elif self.model_type == "gradient_boosting":
            return GradientBoostingClassifier(
                n_estimators=self.n_estimators,
                max_depth=self.max_depth,
                min_samples_leaf=self.min_samples_leaf,
                max_features=self.max_features,
                random_state=self.random_state,
            )
        else:
            return LogisticRegression(
                max_iter=1000,
                C=0.1,
                class_weight="balanced",
                random_state=self.random_state,
            )

    def train(
        self,
        X: pd.DataFrame,
        y: pd.Series,
        test_size: float = 0.2,
    ) -> Dict[str, Any]:
        """
        Train the classifier on features and labels.

        Args:
            X: Feature DataFrame
            y: Labels series (regime names)
            test_size: Fraction of data for testing

        Returns:
            Dict with train/test scores and feature importance
        """
        from sklearn.metrics import classification_report, accuracy_score

        # Drop rows with NaN
        valid_mask = X.notna().all(axis=1) & y.notna()
        X_clean = X[valid_mask]
        y_clean = y[valid_mask]

        # Train/test split (time-based, not random)
        split_idx = int(len(X_clean) * (1 - test_size))
        X_train = X_clean.iloc[:split_idx]
        X_test = X_clean.iloc[split_idx:]
        y_train = y_clean.iloc[:split_idx]
        y_test = y_clean.iloc[split_idx:]

        # Create and train model
        self.model = self._create_model()
        self.feature_names_ = list(X_train.columns)
        self.model.fit(X_train, y_train)
        self.classes_ = list(self.model.classes_)

        # Evaluate
        train_pred = self.model.predict(X_train)
        test_pred = self.model.predict(X_test)

        results = {
            "train_accuracy": accuracy_score(y_train, train_pred),
            "test_accuracy": accuracy_score(y_test, test_pred),
            "train_report": classification_report(y_train, train_pred, output_dict=True),
            "test_report": classification_report(y_test, test_pred, output_dict=True),
            "n_train": len(X_train),
            "n_test": len(X_test),
        }

        # Feature importance (for tree-based models)
        if hasattr(self.model, "feature_importances_"):
            results["feature_importance"] = dict(
                sorted(
                    zip(
                        self.feature_names_,
                        self.model.feature_importances_,
                    ),
                    key=lambda x: x[1],
                    reverse=True,
                )[:20]
            )

        return results

    def predict(self, X: pd.DataFrame) -> pd.Series:
        """
        Predict regime for new data.

        Args:
            X: Feature DataFrame

        Returns:
            Series of predicted regime names
        """
        if self.model is None:
            raise ValueError("Model not trained. Call train() first.")

        predictions = self.model.predict(X.fillna(0))
        return pd.Series(predictions, index=X.index, name="predicted_regime")

    def predict_proba(self, X: pd.DataFrame) -> pd.DataFrame:
        """
        Get prediction probabilities.

        Args:
            X: Feature DataFrame

        Returns:
            DataFrame with probability for each regime
        """
        if self.model is None:
            raise ValueError("Model not trained. Call train() first.")

        probs = self.model.predict_proba(X.fillna(0))
        prob_df = pd.DataFrame(
            probs,
            columns=self.model.classes_,
            index=X.index,
        )
        return prob_df

    def get_feature_importance(self, top_n: int = 20) -> pd.DataFrame:
        """
        Get feature importance scores.

        Args:
            top_n: Number of top features to return

        Returns:
            DataFrame with feature names and importance scores
        """
        if not hasattr(self.model, "feature_importances_"):
            # For logistic regression, use coefficients
            if hasattr(self.model, "coef_"):
                importance = np.abs(self.model.coef_).mean(axis=0)
                return (
                    pd.DataFrame(
                        {
                            "feature": self.feature_names_,
                            "importance": importance,
                        }
                    )
                    .sort_values("importance", ascending=False)
                    .head(top_n)
                )
            return pd.DataFrame()

        return (
            pd.DataFrame(
                {
                    "feature": self.feature_names_,
                    "importance": self.model.feature_importances_,
                }
            )
            .sort_values("importance", ascending=False)
            .head(top_n)
        )

    def walk_forward_validation(
        self,
        X: pd.DataFrame,
        y: pd.Series,
        train_size: int = 500,
        step_size: int = 100,
    ) -> Dict[str, List[float]]:
        """
        Walk-forward validation to detect overfitting.

        Args:
            X: Feature DataFrame
            y: Labels series
            train_size: Initial training window size
            step_size: Step size for expanding window

        Returns:
            Dict with train_score and test_score lists
        """
        from sklearn.metrics import accuracy_score

        results = {"train_score": [], "test_score": []}
        start = 0

        while start + train_size < len(X):
            end = min(start + train_size + step_size, len(X))
            test_end = min(start + train_size + step_size, len(X))

            # Train on expanding window
            X_train = X.iloc[start : start + train_size]
            y_train = y.iloc[start : start + train_size]
            X_test = X.iloc[start + train_size : end]
            y_test = y.iloc[start + train_size : end]

            if len(X_test) == 0:
                break

            # Clean NaN
            valid_train = X_train.notna().all(axis=1) & y_train.notna()
            valid_test = X_test.notna().all(axis=1) & y_test.notna()

            if valid_train.sum() == 0 or valid_test.sum() == 0:
                start += step_size
                continue

            model = self._create_model()
            model.fit(X_train[valid_train], y_train[valid_train])

            train_pred = model.predict(X_train[valid_train])
            test_pred = model.predict(X_test[valid_test])

            results["train_score"].append(accuracy_score(y_train[valid_train], train_pred))
            results["test_score"].append(accuracy_score(y_test[valid_test], test_pred))

            start += step_size

        return results

    def purged_kfold_validation(
        self,
        X: pd.DataFrame,
        y: pd.Series,
        n_splits: int = 5,
        test_size: int = 100,
        gap: int = 20,
    ) -> Dict[str, Any]:
        """
        Purged K-Fold cross-validation with temporal splits to prevent look-ahead bias.

        Args:
            X: Feature DataFrame with datetime index
            y: Labels series
            n_splits: Number of CV folds
            test_size: Number of samples in test set per fold
            gap: Number of samples to exclude between train and test (temporal gap)

        Returns:
            Dict with mean/std train/test scores and per-fold details
        """
        from sklearn.metrics import accuracy_score

        n_total = len(X)
        min_train_size = n_total // (n_splits + 1)

        if min_train_size < test_size:
            raise ValueError(
                f"Dataset too small for {n_splits} splits. Need at least "
                f"{(n_splits + 1) * test_size} samples, got {n_total}."
            )

        fold_results = []
        train_scores = []
        test_scores = []

        for i in range(n_splits):
            train_end = (i * (n_total - test_size)) // n_splits
            test_start = train_end + gap
            test_end = test_start + test_size

            if test_end > n_total:
                break

            X_train = X.iloc[:train_end]
            y_train = y.iloc[:train_end]
            X_test = X.iloc[test_start:test_end]
            y_test = y.iloc[test_start:test_end]

            valid_train = X_train.notna().all(axis=1) & y_train.notna()
            valid_test = X_test.notna().all(axis=1) & y_test.notna()

            if valid_train.sum() < 50 or valid_test.sum() < 10:
                continue

            model = self._create_model()
            model.fit(X_train[valid_train], y_train[valid_train])

            train_pred = model.predict(X_train[valid_train])
            test_pred = model.predict(X_test[valid_test])

            train_acc = accuracy_score(y_train[valid_train], train_pred)
            test_acc = accuracy_score(y_test[valid_test], test_pred)

            train_scores.append(train_acc)
            test_scores.append(test_acc)

            fold_results.append(
                {
                    "fold": i + 1,
                    "train_size": valid_train.sum(),
                    "test_size": valid_test.sum(),
                    "train_accuracy": train_acc,
                    "test_accuracy": test_acc,
                }
            )

        if not train_scores:
            return {"error": "No valid folds created"}

        return {
            "mean_train_accuracy": np.mean(train_scores),
            "std_train_accuracy": np.std(train_scores),
            "mean_test_accuracy": np.mean(test_scores),
            "std_test_accuracy": np.std(test_scores),
            "overfit_gap": np.mean(train_scores) - np.mean(test_scores),
            "n_folds": len(fold_results),
            "fold_details": fold_results,
        }
